---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
      - github-actions
  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
      - terraform
