---
name: Readme

on:
  pull_request:

jobs:
  readme:
    name: Generate Readme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Generate Readme
        uses: terraform-docs/gh-actions@v0.11.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-commit-message: "docs: Generate README.md"
          git-push: true
