---
name: Readme

on:
  pull_request:

permissions:
  contents: write

jobs:
  readme:
    uses: dhoppeIT/github-reusable-workflows/.github/workflows/docs.yaml@main
    with:
      working-dir: .,examples/workspace_with_vcs,examples/workspace_without_vcs
      output-file: README.md
      git-commit-message: "docs: Generate README.md"
      git-push: true
