---
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: ${{ github.repository_owner == 'dhoppeIT' }}
    uses: dhoppeIT/github-reusable-workflows/.github/workflows/release.yaml@main
    with:
      release-type: terraform-module
      bump-minor-pre-major: true
      pull-request-title-pattern: "chore${scope}: Release${component} ${version}"
